import type { Word } from '../data/types.ts'
import { letterOf, shardOf } from './shard.ts'

// Generated by scripts/build-words.mjs. Served from public/data/.
const BASE = import.meta.env.BASE_URL

export interface WordIndex {
  /** Headwords in display order: most common first. */
  sorted: string[]
  set: Set<string>
}

const letterPromises = new Map<string, Promise<WordIndex>>()
const shardPromises = new Map<string, Promise<Record<string, Word[]>>>()

function getJson<T>(path: string): Promise<T> {
  return fetch(`${BASE}data/${path}`).then((r) => {
    if (!r.ok) throw new Error(`${path} ${r.status}`)
    return r.json() as Promise<T>
  })
}

/** Every headword starting with this letter, loaded on the first keystroke. */
export function loadLetter(letter: string): Promise<WordIndex> {
  let promise = letterPromises.get(letter)
  if (!promise) {
    promise = getJson<string[]>(`i/${letter}.json`)
      .then((sorted) => ({ sorted, set: new Set(sorted) }))
      .catch(() => ({ sorted: [], set: new Set<string>() }))
    letterPromises.set(letter, promise)
  }
  return promise
}

/** All senses of a headword, or [] if it is not in WordUp. */
export async function loadEntries(word: string): Promise<Word[]> {
  const shard = shardOf(word)
  let promise = shardPromises.get(shard)
  if (!promise) {
    promise = getJson<Record<string, Word[]>>(`w/${shard}.json`).catch(() => ({}))
    shardPromises.set(shard, promise)
  }
  const bucket = await promise
  // Own keys only: "constructor" or "toString" must not resolve to Object's built-ins.
  return Object.hasOwn(bucket, word) ? bucket[word] : []
}

export { letterOf }

export interface OriginGroup {
  id: string
  label: string
  family: string
  /** How many words are listed in this section. */
  words: number
}

export interface OriginsIndex {
  groups: OriginGroup[]
  /** counts[mode][scope][groupId]: mode is ultimate origin or the language it came through. */
  counts: Record<'origin' | 'via', Record<'all' | 'common' | 'top1000', Record<string, number>>>
}

let originsPromise: Promise<OriginsIndex> | null = null
const sectionPromises = new Map<string, Promise<string[]>>()

export function loadOrigins(): Promise<OriginsIndex> {
  originsPromise ??= getJson<OriginsIndex>('origins/index.json')
  return originsPromise
}

/** Every word in an origin section, most common first. */
export function loadSection(id: string): Promise<string[]> {
  let promise = sectionPromises.get(id)
  if (!promise) {
    promise = getJson<string[]>(`origins/${id}.json`).catch(() => [])
    sectionPromises.set(id, promise)
  }
  return promise
}

// Generic cached loader for the explore files (roots, affixes, patterns, sections ...).
const jsonCache = new Map<string, Promise<unknown>>()
export function cachedJson<T>(path: string): Promise<T> {
  let promise = jsonCache.get(path)
  if (!promise) {
    promise = getJson<T>(path)
    promise.catch(() => jsonCache.delete(path))
    jsonCache.set(path, promise)
  }
  return promise as Promise<T>
}

export interface GroupSummary {
  id: number
  n: number
  sample: string[]
  gloss: string | null
}
export interface RootSummary extends GroupSummary {
  root: string
}
export interface AffixSummary extends GroupSummary {
  affix: string
  origin: string
}
export interface PatternStat {
  id: string
  letters: string
  position: 'start' | 'contains' | 'end'
  /** Counted by the language English took the word from ("via"), or where it ultimately comes from. */
  basis: 'via' | 'origin'
  title: string
  text: string
  total: number
  byOrigin: Record<string, number>
  examples: Record<string, string[]>
}
