import type { Word } from '../data/types.ts'
import { shardOf } from './shard.ts'

// Generated by scripts/build-words.mjs. Served from public/data/.
const BASE = import.meta.env.BASE_URL

export interface WordIndex {
  /** Shortest first, then alphabetical, so prefix results read naturally. */
  sorted: string[]
  set: Set<string>
  license: string
}

let indexPromise: Promise<WordIndex> | null = null
const shardPromises = new Map<string, Promise<Record<string, Word[]>>>()

export function loadIndex(): Promise<WordIndex> {
  indexPromise ??= fetch(`${BASE}data/index.json`)
    .then((r) => {
      if (!r.ok) throw new Error(`index ${r.status}`)
      return r.json() as Promise<{ words: string[]; license: string }>
    })
    .then((json) => {
      const sorted = [...json.words].sort((a, b) => a.length - b.length || a.localeCompare(b))
      return { sorted, set: new Set(json.words), license: json.license }
    })
  return indexPromise
}

/** All senses of a headword, or [] if it is not in WordUp. */
export async function loadEntries(word: string): Promise<Word[]> {
  const shard = shardOf(word)
  let promise = shardPromises.get(shard)
  if (!promise) {
    promise = fetch(`${BASE}data/w/${shard}.json`).then((r) => {
      if (!r.ok) throw new Error(`shard ${shard} ${r.status}`)
      return r.json() as Promise<Record<string, Word[]>>
    })
    shardPromises.set(shard, promise)
  }
  const bucket = await promise
  return bucket[word] ?? []
}
