import type { Word } from '../data/types.ts'
import { letterOf, shardOf } from './shard.ts'

// Generated by scripts/build-words.mjs. Served from public/data/.
const BASE = import.meta.env.BASE_URL

export interface WordIndex {
  /** Headwords in display order: most common first. */
  sorted: string[]
  set: Set<string>
}

const letterPromises = new Map<string, Promise<WordIndex>>()
const shardPromises = new Map<string, Promise<Record<string, Word[]>>>()

function getJson<T>(path: string): Promise<T> {
  return fetch(`${BASE}data/${path}`).then((r) => {
    if (!r.ok) throw new Error(`${path} ${r.status}`)
    return r.json() as Promise<T>
  })
}

/** Every headword starting with this letter, loaded on the first keystroke. */
export function loadLetter(letter: string): Promise<WordIndex> {
  let promise = letterPromises.get(letter)
  if (!promise) {
    promise = getJson<string[]>(`i/${letter}.json`)
      .then((sorted) => ({ sorted, set: new Set(sorted) }))
      .catch(() => ({ sorted: [], set: new Set<string>() }))
    letterPromises.set(letter, promise)
  }
  return promise
}

/** All senses of a headword, or [] if it is not in WordUp. */
export async function loadEntries(word: string): Promise<Word[]> {
  const shard = shardOf(word)
  let promise = shardPromises.get(shard)
  if (!promise) {
    promise = getJson<Record<string, Word[]>>(`w/${shard}.json`).catch(() => ({}))
    shardPromises.set(shard, promise)
  }
  const bucket = await promise
  // Own keys only: "constructor" or "toString" must not resolve to Object's built-ins.
  return Object.hasOwn(bucket, word) ? bucket[word] : []
}

export { letterOf }
